apiVersion: v1
entries:
  secrets-store-sync-controller:
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2024-08-23T00:17:18.208333963Z"
    description: A Helm chart to install the Secrets Store Sync Controller and its
      associated resources inside a Kubernetes cluster.
    digest: 9ce87909c3468b7c3c5b50a6f7472cf34a0945f98aa75228ce20afdc3bfa74e7
    kubeVersion: '>=1.27.0'
    name: secrets-store-sync-controller
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-sync-controller/charts/secrets-store-sync-controller-0.0.1.tgz
    version: 0.0.1
generated: "2024-08-23T00:17:18.207200833Z"
